### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by MircoCagni** [quantumcored/paradoxia#1]
paradoxia> help
Traceback (most recent call last):
  File "paradoxia", line 18, in <module>
    main()
  File "paradoxia", line 16, in main
    console()
  File "/home/mirco/Documenti/paradoxia/kernel/pdmain.py", line 372, in console
    args = command.split()
AttributeError: '_Helper' object has no attribute 'split'

**Comment by quantumcore** [comment]
Did you run it like this : 
```bash
cd paradoxia
python3 -m pip install -r requirements.txt
chmod +x paradoxia
sudo ./paradoxia
```
I can't reproduce the error, Can you tell me how you're running it? Do you have all modules installed? And what's your Operating system?

**Comment by MircoCagni** [comment]
> Did you run it like this :
> 
> ```shell
> cd paradoxia
> python3 -m pip install -r requirements.txt
> chmod +x paradoxia
> sudo ./paradoxia
> ```
> 
> I can't reproduce the error, Can you tell me how you're running it? Do you have all modules installed? And what's your Operating system?

Nvm last night I have resolve it ty a lot

**Comment by CezarFSociety** [comment]
what was the error solution?
