### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by CezarFSociety** [quantumcored/paradoxia#2]
using Ubuntu 19.10
input: sudo ./paradoxia
output: Traceback (most recent call last):
  File "./paradoxia", line 8, in <module>
    from kernel.infodb import *
  File "/home/lenovo/Desktop/Programs/Hacking/paradoxia/kernel/infodb.py", line 7, in <module>
    import geoip2.database
ModuleNotFoundError: No module named 'geoip2'

----------------------
I have installed the requirements, updated and upgraded

**Comment by quantumcore** [comment]
If it says that ``no module named 'geoip2`` that means that all requirements aren't installed. This error is for Paradoxia rat because that makes use of the geoip2 module. 
[Here](https://raw.githubusercontent.com/quantumcored/paradoxia/master/requirements.txt) is a list of all requirements. If it fails to install by the setup script you may do : 
```
$ python3 -m pip install -r requirements.txt
```
OR 
```
$ python3 -m pip install < missing module >
```

**Comment by CezarFSociety** [comment]
i did do that. Installed it single handedly.
When i try to do install requirements the output is: 
C:\home\lenovo\Desktop\Programs\Hacking\Bitne Skripte\BOTNET\mass ###\paradoxia> python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geoip2 in /home/lenovo/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.0.0)
Requirement already satisfied: configparser in /home/lenovo/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (4.0.2)
Requirement already satisfied: plyer in /home/lenovo/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.4.3)
Requirement already satisfied: tqdm in /home/lenovo/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (4.45.0)
Collecting names
  Using cached names-0.3.0.tar.gz (789 kB)
Collecting random-username
  Using cached random_username-1.0.2-py3-none-any.whl (6.7 kB)
Requirement already satisfied: requests in /home/lenovo/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (2.23.0)
Collecting stem
  Using cached stem-1.8.0.tar.gz (2.9 MB)
Collecting instagram-py
  Using cached instagram-py-2.0.7.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehgszf91/instagram-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehgszf91/instagram-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n90tcydu
         cwd: /tmp/pip-install-ehgszf91/instagram-py/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ehgszf91/instagram-py/setup.py", line 13, in <module>
        from InstagramPy import __version__
      File "/tmp/pip-install-ehgszf91/instagram-py/InstagramPy/__init__.py", line 11, in <module>
        from .InstagramPySession import InstagramPySession, DEFAULT_PATH
      File "/tmp/pip-install-ehgszf91/instagram-py/InstagramPy/InstagramPySession.py", line 12, in <module>
        from stem import Signal
    ModuleNotFoundError: No module named 'stem'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

-------------------------------
But when i try to do sudo ./paradoxia the output it:
Traceback (most recent call last):
  File "./paradoxia", line 8, in <module>
    from kernel.infodb import *
  File "/home/lenovo/Desktop/Programs/Hacking/Bitne Skripte/BOTNET/mass ###/paradoxia/kernel/infodb.py", line 7, in <module>
    import geoip2.database
ModuleNotFoundError: No module named 'geoip2'

And it wont read the already downloaded geoip2

**Comment by quantumcore** [comment]
```
import geoip2.database
ModuleNotFoundError: No module named 'geoip2'
```
Your python installation seems to be corrupted. 
https://stackoverflow.com/questions/15052206/python-pip-install-module-is-not-found-how-to-link-python-to-pip-location
