### ISSUE TITLE
BRUTE FORCE ATTACK

### ISSUE THREAD

**Issue by osurr** [quantumcored/paradoxia#3]
does it work ???How does it work

**Comment by quantumcore** [comment]
To BruteForce you need to use Iris. 
Read here : [Iris guide](https://github.com/quantumcored/paradoxia/tree/master/iris)
```
cd iris
./iris.py -bruteforce-instagram true -instagram-user < username > -instagram-list /usr/share/wordlists/rockyou.txt 
```

**Comment by osurr** [comment]
not working. I'm getting the error

**Comment by quantumcore** [comment]
What Error are you getting?

**Comment by osurr** [comment]
bash: beklenmeyen dizgecik `newline' yakınında sözdizimi hatası



sorry 
I couldn't translate it into English :(

**Comment by osurr** [comment]
can you please help

**Comment by quantumcore** [comment]
```

syntax error near unexpected string newline
```
```bash
cd paradoxia
python3 -m pip install -r requirements.txt
chmod +x paradoxia
sudo ./paradoxia
```
